# docker-compose.yml
services:
  app:
    image: python:3.11-alpine
    volumes:
      - ./tests:/tests
    working_dir: /tests
    depends_on:
      - mongodb # arranca despues de mongodb

  mongodb:
    image: mongo:6.0
    volumes:
      - ./datos:/data/db
    ports:
      - 27017:27017
